app:
  resource: '@AppBundle/Controller/'
  type: annotation
admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /teacher

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /teacher
